### ISSUE TITLE
Long term sessions❓

### ISSUE THREAD

**Issue by brandonserna** [mattaschmann/aws-saml-login#2]
Thank you for this super useful utility @mattaschmann , I've been using it frequently. Do you know if there's anyway to run this headless with cached credentials? My org seems to have a session duration limit and I'd love to find some way to refresh on a schedule or make it slightly quicker

I hope this is not something I missed in the help docs but this is how I've been invoking and it's working __great__ I think it uses the defaultsession time of 3600 or 1hr

```sh
aws-saml-login url
```

**Comment by mattaschmann** [comment]
@brandonserna 

Glad you like the utility!  There is a `-d` argument which will allow you to specify a session duration if you want (see: https://docs.aws.amazon.com/STS/latest/APIReference/API_GetSessionToken.html).  The default for amazon is 3600, but if your organization allows it you can set it higher.  If you want to automate the process a bit for re-logins you can use the `-r` flag, which will save some of your choices.

For example:
```
aws-saml-login -r <profile name> -d 28800
```
will refresh the profile <profile name> for 8 hours.

As far as caching credentials, I found that difficult as chromium clears out it's cache every run.  I was also hesitant to implement saving credentials in a local file for obvious reasons.

**Comment by mattaschmann** [comment]
Just to give more info before I close this ticket, this stackoverflow post has a good discussion of this:  https://stackoverflow.com/questions/48608971/how-to-manage-log-in-session-through-headless-chrome

I've tried many of those options (saving cookies in a json and reloading, setting the userDataDir, etc...), with no success at saving login sessions.

Feel free to try and tackle this particular problem, I gave up on it as it was taking more time to solve then I felt it was worth.
